# kubectl -n alerts apply -f deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-trap-handler-deployment
  labels:
    app: snmp-trap-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snmp-trap-handler
  template:
    metadata:
      labels:
        app: snmp-trap-handler
      annotations:
        nautilus.dellemc.com/pravega-environment: "alerts-pravega"
    spec:
      serviceAccountName: alerts-pravega
      containers:
      - name: snmp-trap-handler
        image: devops-repo.isus.emc.com:8116/pravega/snmp-trap-handler
        ports:
        - containerPort: 1162
          protocol: UDP
        volumeMounts:
        - name: quarkus-config-volume
          mountPath: /deployments/config
      volumes:
      - name: quarkus-config-volume
        configMap:
          name: snmp-trap-handler
