# kubectl -n alerts apply -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-handler-service
spec:
  type: LoadBalancer
  selector:
    app: snmp-trap-handler
  ports:
    - name: snmp
      protocol: UDP
      port: 162
      targetPort: 1162
